### ISSUE TITLE
Concurrent firing of a single kiln

### ISSUE THREAD

**Issue by S11001001** [straszheimjeffrey/The-Kiln#3]
What's to be the story on concurrent firing of a kiln?

S11001001/The-Kiln@2d687169e38cd4ed5d2f93f7740939362c654971 is a pretty good summary of what the expected results would be from a simple, per-kiln locking approach, or anything providing equivalent semantics.  I spun it 5 times in the test to be sure, but it seems to sufficiently trash the kiln state to cause failures more than half the time, at least on my machine.

Said test also halfheartedly tries to cause a deadly embrace in the case of a naïve per-clay-`delay`-based concurrency solution.

Some of the concurrency could be preserved if clay expressions could be evalled more often in the concurrent-access case.

**Comment by straszheimjeffrey** [comment]
I don't really plan to support concurrent update of a single kiln -- it's just too tricky. Kilns do use refs, but these are not for thread safety. Instead, they are to allow seamless co-existance for _other code_ that runs in transactions, which may access legitimately concurrent structures.

Eventually _most_ clay will be run inside of an io! guard, with specially marked clay being allowed to run in transactions. I'm still thinking through how that might work.

**Comment by straszheimjeffrey** [comment]
I have not done the io! stuff as I planned. I'm still not sure if it is correct. What I am certain of is this: kilns are not multithreaded. Their principle use case remains web requests. Keep in mind, clays will call impure functions: IO, database, templates, etc. To make that all play nice with threads would be very tricky.
