### ISSUE TITLE
In sample, please use :require instead of :use, or add :only to :use clauses.

### ISSUE THREAD

**Issue by hozumi** [straszheimjeffrey/The-Kiln#6]
https://github.com/straszheimjeffrey/The-Kiln/blob/master/sample/src/sample/response.clj
I have no clue where request-uri, response-type and etc are defined.

**Comment by straszheimjeffrey** [comment]
Those are defined here:

https://github.com/straszheimjeffrey/The-Kiln/blob/master/kiln-ring/src/kiln_ring/request.clj

But you make a good point. It would very very much easier for people if :require were used. In fact, I should use it for most of the sample. I will try to find time in the next couple days to make the change.

Thanks.

**Comment by hozumi** [comment]
Thank you for the consideration.

**Comment by straszheimjeffrey** [comment]
All set!

Thanks. It was a good suggestion.

**Comment by hozumi** [comment]
Thanks.
